Handling exceptions in the agent
elastic/apm-agent-dotnet pull request #1161
Opened 2021-02-01 17:41 UTC by gregkalapos

- Remove InstanceAlreadyCreatedException, instead we log now
- Introduce DiagnosticListenerBase class which handles errors in OnNext

2021-02-01 18:21 UTC, apmmachine commented
## :grey_exclamation: Build Aborted
  
  > There is a new build on-going so the previous on-going builds have been aborted.
  


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-dotnet%2Fapm-agent-dotnet-mbp%2FPR-1161/detail/PR-1161/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-dotnet%2Fapm-agent-dotnet-mbp%2FPR-1161/detail/PR-1161/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-dotnet%2Fapm-agent-dotnet-mbp%2FPR-1161/detail/PR-1161/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-dotnet%2Fapm-agent-dotnet-mbp%2FPR-1161/detail/PR-1161/1//artifacts) 

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats


* Build Cause: `Pull request #1161 opened`


* Reason: `Aborted from #2`


* * Start Time: 2021-02-01T17:41:18.821+0000


* Duration: 40 min 13 sec


* Commit: a776e9e20bd4d260cb89aa7556eeb763d7d39565



#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 15  |
| Passed       | 674  |
| Skipped      | 2 |
| Total        | 691   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->

  ### Test errors [![15](https://img.shields.io/badge/15%20-red)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-dotnet%2Fapm-agent-dotnet-mbp%2FPR-1161/detail/PR-1161/1//tests)
<details><summary>Expand to view the tests failures</summary><p>
    > Show only the first 10 test failures
    
##### `DistributedTracingAspNetCoreTests.Elastic.Apm.AspNetCore.Tests.DistributedTracingAspNetCoreTests.DistributedTraceAcross2ServicesWithUseElasticTraceParentTrue – Elastic.Apm.AspNetCore.Tests.DistributedTracingAspNetCoreTests`


<ul>
<details><summary>Expand to view the error details</summary><p>

```
 Expected collection {"Host", "Request-Id"} to contain "traceparent". 
 ```
</p></details>
<details><summary>Expand to view the stacktrace</summary><p>

```
 Expected collection {"Host", "Request-Id"} to contain "traceparent".
Stack Trace:
   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Execution\XUnit2TestFramework.cs:line 32
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Execution\AssertionScope.cs:line 181
   at FluentAssertions.Collections.SelfReferencingCollectionAssertions`2.Contain(T expected, String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Collections\SelfReferencingCollectionAssertions.cs:line 431
   at Elastic.Apm.AspNetCore.Tests.DistributedTracingAspNetCoreTests.DistributedTraceAcross2ServicesWithUseElasticTraceParentTrue()
--- End of stack trace from previous location where exception was thrown --- 
 ```
</p></details>
</ul>
    
##### `DistributedTracingAspNetCoreTests.Elastic.Apm.AspNetCore.Tests.DistributedTracingAspNetCoreTests.DistributedTraceAcross2ServicesWithUseElasticTraceParentFalse – Elastic.Apm.AspNetCore.Tests.DistributedTracingAspNetCoreTests`


<ul>
<details><summary>Expand to view the error details</summary><p>

```
 Expected collection {"Host", "Request-Id"} to contain "traceparent". 
 ```
</p></details>
<details><summary>Expand to view the stacktrace</summary><p>

```
 Expected collection {"Host", "Request-Id"} to contain "traceparent".
Stack Trace:
   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Execution\XUnit2TestFramework.cs:line 32
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Execution\AssertionScope.cs:line 181
   at FluentAssertions.Collections.SelfReferencingCollectionAssertions`2.Contain(T expected, String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Collections\SelfReferencingCollectionAssertions.cs:line 431
   at Elastic.Apm.AspNetCore.Tests.DistributedTracingAspNetCoreTests.DistributedTraceAcross2ServicesWithUseElasticTraceParentFalse()
--- End of stack trace from previous location where exception was thrown --- 
 ```
</p></details>
</ul>
    
##### `DistributedTracingAspNetCoreTests.Elastic.Apm.AspNetCore.Tests.DistributedTracingAspNetCoreTests.NonSampledDistributedTraceAcross2Service – Elastic.Apm.AspNetCore.Tests.DistributedTracingAspNetCoreTests`


<ul>
<details><summary>Expand to view the error details</summary><p>

```
 Expected _payloadSender1.Spans to be false, but found True. 
 ```
</p></details>
<details><summary>Expand to view the stacktrace</summary><p>

```
 Expected _payloadSender1.Spans to be false, but found True.
Stack Trace:
   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Execution\XUnit2TestFramework.cs:line 32
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Execution\AssertionScope.cs:line 181
   at FluentAssertions.Primitives.BooleanAssertions.BeFalse(String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Primitives\BooleanAssertions.cs:line 39
   at Elastic.Apm.AspNetCore.Tests.DistributedTracingAspNetCoreTests.NonSampledDistributedTraceAcross2Service() in C:\Users\jenkins\workspace\net_apm-agent-dotnet-mbp_PR-1161\apm-agent-dotnet\test\Elastic.Apm.AspNetCore.Tests\DistributedTracingAspNetCoreTests.cs:line 154
--- End of stack trace from previous location where exception was thrown --- 
 ```
</p></details>
</ul>
    
##### `DistributedTracingAspNetCoreTests.Elastic.Apm.AspNetCore.Tests.DistributedTracingAspNetCoreTests.DistributedTraceAcross2Service – Elastic.Apm.AspNetCore.Tests.DistributedTracingAspNetCoreTests`


<ul>
<details><summary>Expand to view the error details</summary><p>

```
 System.InvalidOperationException : Sequence contains no matching element 
 ```
</p></details>
<details><summary>Expand to view the stacktrace</summary><p>

```
 System.InvalidOperationException : Sequence contains no matching element
Stack Trace:
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Elastic.Apm.AspNetCore.Tests.DistributedTracingAspNetCoreTests.DistributedTraceAcross2Service() in C:\Users\jenkins\workspace\net_apm-agent-dotnet-mbp_PR-1161\apm-agent-dotnet\test\Elastic.Apm.AspNetCore.Tests\DistributedTracingAspNetCoreTests.cs:line 102
--- End of stack trace from previous location where exception was thrown --- 
 ```
</p></details>
</ul>
    
##### `DistributedTracingAspNetCoreTests.Elastic.Apm.AspNetCore.Tests.DistributedTracingAspNetCoreTests.DistributedTraceAcross2ServicesWithTraceState – Elastic.Apm.AspNetCore.Tests.DistributedTracingAspNetCoreTests`


<ul>
<details><summary>Expand to view the error details</summary><p>

```
 Expected dictionary {[Host, localhost:5050], [Request-Id, 00-054f13c83de5244f8c5c6ffc67016922-df9cace402499845-01]} to contain key "tracestate". 
 ```
</p></details>
<details><summary>Expand to view the stacktrace</summary><p>

```
 Expected dictionary {[Host, localhost:5050], [Request-Id, 00-054f13c83de5244f8c5c6ffc67016922-df9cace402499845-01]} to contain key "tracestate".
Stack Trace:
   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Execution\XUnit2TestFramework.cs:line 32
   at FluentAssertions. [...]

2021-02-01 19:33 UTC, bmorelli25 reviewed
Troubleshooting docs look fine 👍

2021-02-05 00:49 UTC, russcam requested changes
On the whole, the changes look good.

The removal of `InstanceAlreadyCreatedException` is a behavioural change. In theory, a thrown `InstanceAlreadyCreatedException` would bubble up to the application which I would suspect would be noticed and fixed by a user early, as the agent would not be functioning otherwise. The removal of `InstanceAlreadyCreatedException` could be viewed as a positive behavioural change, as it's removal leaves an application in no less of a worse state. On the other hand, where an exception would have been thrown, an error is now logged, which is less visible and could leave a user in a state where they believe a change has taken effect (e.g. changed the setup of the agent) when it has not. This looks like an acceptable minor version change.

The introduction of `DiagnosticListenerBase` _looks_ binary compatible - do the differ results flag anything?

2021-02-05 00:49 UTC, russcam commented on src/Elastic.Apm/Agent.cs
> +				agentComponents?.Logger?.Error()?.Log("The singleton APM agent has already been instantiated and can no longer be configured.");
```suggestion
				agentComponents?.Logger?.Error()?.Log("The singleton APM agent has already been instantiated and can no longer be configured. Using existing instance");
```

2021-02-05 00:49 UTC, russcam commented on src/Elastic.Apm/DiagnosticListeners/DiagnosticListenerBase.cs
> +		protected readonly IApmLogger Logger;
```suggestion
		protected IApmLogger Logger { get; };
```

2021-02-05 00:49 UTC, russcam commented on src/Elastic.Apm/DiagnosticListeners/DiagnosticListenerBase.cs
> +		protected readonly IApmAgent ApmAgent;
```suggestion
		protected IApmAgent ApmAgent { get; }
```

2021-02-05 00:49 UTC, russcam commented on src/Elastic.Apm/DiagnosticListeners/DiagnosticListenerBase.cs
> +		public void OnCompleted() { }
```suggestion
		public virtual void OnCompleted() { }
```

2021-02-11 04:24 UTC, apmmachine commented
## :grey_exclamation: Build Aborted
  
  > Either there was a build timeout or someone aborted the build.'}
  


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-dotnet%2Fapm-agent-dotnet-mbp%2FPR-1161/detail/PR-1161/7//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-dotnet%2Fapm-agent-dotnet-mbp%2FPR-1161/detail/PR-1161/7//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-dotnet%2Fapm-agent-dotnet-mbp%2FPR-1161/detail/PR-1161/7//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-dotnet%2Fapm-agent-dotnet-mbp%2FPR-1161/detail/PR-1161/7//artifacts) 

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats


* Build Cause: `Branch indexing`



* Start Time: 2021-02-11T02:20:23.323+0000


* Duration: 124 min 33 sec


* Commit: aed141e0ba393cbe6d51f0ab7b90817f94310a03



#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 15  |
| Passed       | 743  |
| Skipped      | 2 |
| Total        | 760   |


#### Trends :test_tube:


![Image of Build Times](https://apm-ci.elastic.co/job/apm-agent-dotnet/job/apm-agent-dotnet-mbp/job/PR-1161/buildTimeGraph/png)


![Image of Tests](https://apm-ci.elastic.co/job/apm-agent-dotnet/job/apm-agent-dotnet-mbp/job/PR-1161/7/testReport/history/countGraph/png?start=0&amp;end=25)


</p>
</details>

<!-- TEST RESULTS IF ANY-->

  ### Test errors [![15](https://img.shields.io/badge/15%20-red)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-dotnet%2Fapm-agent-dotnet-mbp%2FPR-1161/detail/PR-1161/7//tests)
<details><summary>Expand to view the tests failures</summary><p>
    > Show only the first 10 test failures
    
##### `Initializing / Parallel / Windows .NET Core / Test / DistributedTracingAspNetCoreTests.Elastic.Apm.AspNetCore.Tests.DistributedTracingAspNetCoreTests.DistributedTraceAcross2ServicesWithUseElasticTraceParentFalse – Elastic.Apm.AspNetCore.Tests.DistributedTracingAspNetCoreTests`


<ul>
<details><summary>Expand to view the error details</summary><p>

```
 Expected collection {"Host", "Request-Id"} to contain "traceparent". 
 ```
</p></details>
<details><summary>Expand to view the stacktrace</summary><p>

```
 Expected collection {"Host", "Request-Id"} to contain "traceparent".
Stack Trace:
   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Execution\XUnit2TestFramework.cs:line 32
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Execution\AssertionScope.cs:line 181
   at FluentAssertions.Collections.SelfReferencingCollectionAssertions`2.Contain(T expected, String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Collections\SelfReferencingCollectionAssertions.cs:line 431
   at Elastic.Apm.AspNetCore.Tests.DistributedTracingAspNetCoreTests.DistributedTraceAcross2ServicesWithUseElasticTraceParentFalse()
--- End of stack trace from previous location where exception was thrown --- 
 ```
</p></details>
</ul>
    
##### `Initializing / Parallel / Windows .NET Core / Test / DistributedTracingAspNetCoreTests.Elastic.Apm.AspNetCore.Tests.DistributedTracingAspNetCoreTests.DistributedTraceAcross2ServicesWithTraceState – Elastic.Apm.AspNetCore.Tests.DistributedTracingAspNetCoreTests`


<ul>
<details><summary>Expand to view the error details</summary><p>

```
 Expected dictionary {[Host, localhost:5050], [Request-Id, 00-530115206421a84e8bd9f666cb79815f-9380ec49170eb943-01]} to contain key "tracestate". 
 ```
</p></details>
<details><summary>Expand to view the stacktrace</summary><p>

```
 Expected dictionary {[Host, localhost:5050], [Request-Id, 00-530115206421a84e8bd9f666cb79815f-9380ec49170eb943-01]} to contain key "tracestate".
Stack Trace:
   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Execution\XUnit2TestFramework.cs:line 32
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Execution\AssertionScope.cs:line 181
   at FluentAssertions.Collections.GenericDictionaryAssertions`2.ContainKeys(IEnumerable`1 expected, String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Collections\GenericDictionaryAssertions.cs:line 585
   at FluentAssertions.Collections.GenericDictionaryAssertions`2.ContainKey(TKey expected, String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Collections\GenericDictionaryAssertions.cs:line 514
   at Elastic.Apm.AspNetCore.Tests.DistributedTracingAspNetCoreTests.DistributedTraceAcross2ServicesWithTraceState()
--- End of stack trace from previous location where exception was thrown --- 
 ```
</p></details>
</ul>
    
##### `Initializing / Parallel / Windows .NET Core / Test / DistributedTracingAspNetCoreTests.Elastic.Apm.AspNetCore.Tests.DistributedTracingAspNetCoreTests.DistributedTraceAcross2ServicesWithUseElasticTraceParentTrue – Elastic.Apm.AspNetCore.Tests.DistributedTracingAspNetCoreTests`


<ul>
<details><summary>Expand to view the error details</summary><p>

```
 Expected collection {"Host", "Request-Id"} to contain "traceparent". 
 ```
</p></details>
<details><summary>Expand to view the stacktrace</summary><p>

```
 Expected collection {"Host", "Request-Id"} to contain "traceparent".
Stack Trace:
   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Execution\XUnit2TestFramework.cs:line 32
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Execution\AssertionScope.cs:line 181
   at FluentAssertions.Collections.SelfReferencingCollectionAssertions`2.Contain(T expected, String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Collections\SelfReferencingCollectionAssertions.cs:line 431
   at Elastic.Apm.AspNetCore.Tests.DistributedTracingAspNetCoreTests.DistributedTraceAcross2ServicesWithUseElasticTraceParentTrue()
--- End of stack trace from previous location where exception was thrown --- 
 ```
</p></details>
</ul>
    
##### `Initializing / Parallel / Windows .NET Core / Test / DistributedTracingAspNetCoreTests.Elastic.Apm.AspNetCore.Tests.DistributedTracingAspNetCoreTests.NonSampledDistributedTraceAcross2Service – Elastic.Apm.AspNetCore.Tests.DistributedTracingAspNetCoreTests`


<ul>
<details><summary>Expand to view the error details</summary><p>

```
 Expected _payloadSender1.Spans to be false, but found True. 
 ```
</p></details>
<details><summary>Expand to view the stacktrace</summary><p>

```
 Expected _payloadSender1.Spans to be false, but found True.
Stack Trace:
   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Execution\XUnit2TestFramework.cs:line 32
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Execution\AssertionScope.cs:line 181
   at FluentAssertions.Primitives.BooleanAssertions.BeFalse(String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions\Primitives\BooleanAssertions.cs:line 39
   at Elastic.Apm.As [...]

2021-03-02 21:11 UTC, gregkalapos commented
Ready for another round.


> The introduction of `DiagnosticListenerBase` _looks_ binary compatible - do the differ results flag anything?

It flags some unrelated things, which I think don't came from this PR. The `DiagnosticListenerBase` shows up as a new type:

```
<Type Name="Elastic.Apm.DiagnosticListeners.DiagnosticListenerBase" DiffType="New" />
```

Nothing is flagged on types where this is now the parent type except `GrpcClientDiagnosticListener` - I'd expect the same for other derived types. The methods marked as `Deleted` are still there through the parent class, plus they were empty, and on top of that these were there for the framework to call (which it never does), so I think this is fine. 

```
<Module Name="Elastic.Apm.GrpcClient.dll" DiffType="Modified">
    <Type Name="Elastic.Apm.GrpcClient.GrpcClientDiagnosticListener" DiffType="Modified">
      <Method Name="HandleOnNext(KeyValuePair&lt;String, Object&gt;)" DiffType="New" />
      <Method Name="OnCompleted()" DiffType="Deleted" />
      <Method Name="OnError(Exception)" DiffType="Deleted" />
      <Method Name="OnNext(KeyValuePair&lt;String, Object&gt;)" DiffType="Deleted" />
    </Type>
```

2021-03-11 01:38 UTC, russcam approved these changes
Changes LGTM 👍 

One thing to note is that now in some uses of the base `IApmAgent ApmAgent` property, a cast to `ApmAgent` happens in the handling of each diagnostic event. For example, in `HandleOnNext()` in `AspNetCoreDiagnosticListener`. Wondering if in these cases it is worth avoiding the cast each time by assigning the `ApmAgent` in the ctor to a `private ApmAgent _agent` field?

2021-03-11 01:38 UTC, russcam commented on src/Elastic.Apm/DiagnosticListeners/HttpDiagnosticListenerImplBase.cs
> +			var transaction = Agent.Tracer.CurrentTransaction;
```suggestion
			var transaction = ApmAgent.Tracer.CurrentTransaction;
```

2021-03-11 18:40 UTC, gregkalapos commented
> One thing to note is that now in some uses of the base `IApmAgent ApmAgent` property, a cast to `ApmAgent` happens in the handling of each diagnostic event. For example, in `HandleOnNext()` in `AspNetCoreDiagnosticListener`. Wondering if in these cases it is worth avoiding the cast each time by assigning the `ApmAgent` in the ctor to a `private ApmAgent _agent` field?

It makes sense - I don't think it'll make a huge difference, but why not... Specifically in `AspNetCoreDiagnosticListener` I don't think is super relevant, since we only cast once there and the reason for that cast is to get the current config snapshot. Since people already asked about making that public maybe we can get rid of that single cast later. In `EfCoreDiagnosticListener` and `SqlClientDiagnosticListener` we had multiple casts, I think your suggestion would be especially useful there, so I adapted those 2.

2021-03-11 19:38 UTC, merged