Runs tests in blame mode
elastic/apm-agent-dotnet pull request #1193
Opened 2021-02-19 06:24 UTC by russcam

This commit runs tests in blame mode with a blame-hang
timeout of 5 minutes.

2021-02-19 07:01 UTC, apmmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-dotnet%2Fapm-agent-dotnet-mbp%2FPR-1193/detail/PR-1193/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-dotnet%2Fapm-agent-dotnet-mbp%2FPR-1193/detail/PR-1193/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-dotnet%2Fapm-agent-dotnet-mbp%2FPR-1193/detail/PR-1193/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-dotnet%2Fapm-agent-dotnet-mbp%2FPR-1193/detail/PR-1193/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://apm-agent-dotnet_1193.docs-preview.app.elstc.co/diff)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats


* Build Cause: `Pull request #1193 opened`



* Start Time: 2021-02-19T06:24:31.545+0000


* Duration: 37 min 58 sec


* Commit: d6922e544b55691d933627fea0ea45c349e7ea5b



#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 0  |
| Passed       | 16467  |
| Skipped      | 59 |
| Total        | 16526   |


#### Trends :test_tube:


![Image of Build Times](https://apm-ci.elastic.co/job/apm-agent-dotnet/job/apm-agent-dotnet-mbp/job/PR-1193/buildTimeGraph/png)


![Image of Tests](https://apm-ci.elastic.co/job/apm-agent-dotnet/job/apm-agent-dotnet-mbp/job/PR-1193/1/testReport/history/countGraph/png?start=0&amp;end=25)


</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->







### Steps errors [![3](https://img.shields.io/badge/3%20-red)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-dotnet%2Fapm-agent-dotnet-mbp%2FPR-1193/detail/PR-1193/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>

  
  
  
  
  
##### `Test & coverage`
<ul>
<li>Took 0 min 13 sec . View more details on <a href="https://apm-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/apm-agent-dotnet/pipelines/apm-agent-dotnet-mbp/pipelines/PR-1193/runs/1/steps/357/log/?start=0">here</a></li>
<li>Description: <code>.ci/windows/testnet461.bat</code></l1>
</ul>
  
  
  
  
##### `Archive the artifacts`
<ul>
<li>Took 0 min 0 sec . View more details on <a href="https://apm-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/apm-agent-dotnet/pipelines/apm-agent-dotnet-mbp/pipelines/PR-1193/runs/1/steps/372/log/?start=0">here</a></li>
<li>Description: <code>[2021-02-19T06:57:24.988Z] Archiving artifacts
script returned exit code 1</code></l1>
</ul>
  
  
  
  
##### `Build`
<ul>
<li>Took 1 min 30 sec . View more details on <a href="https://apm-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/apm-agent-dotnet/pipelines/apm-agent-dotnet-mbp/pipelines/PR-1193/runs/1/steps/239/log/?start=0">here</a></li>
<li>Description: <code>.ci/windows/dotnet.bat</code></l1>
</ul>
  
  </p>
  </details>



<!-- LOG OUTPUT-->
### Log output

<details><summary>Expand to view the last 100 lines of log output</summary>
<p>

```
[2021-02-19T07:01:18.683Z] [INFO] getVaultSecret: Getting secrets
[2021-02-19T07:01:18.916Z] Masking supported pattern matches of $VAULT_ADDR or $VAULT_ROLE_ID or $VAULT_SECRET_ID
[2021-02-19T07:01:19.600Z] Running in /var/lib/jenkins/workspace/net_apm-agent-dotnet-mbp_PR-1193/apm-agent-dotnet
[2021-02-19T07:01:19.661Z] [INFO] Codecov: Getting branch ref...
[2021-02-19T07:01:19.943Z] Masking supported pattern matches of $GITHUB_TOKEN
[2021-02-19T07:01:20.567Z] [INFO] Codecov: Sending data...
[2021-02-19T07:01:21.137Z] + curl -sSLo codecov.sh https://codecov.io/bash
[2021-02-19T07:01:21.530Z] + bash codecov.sh
[2021-02-19T07:01:21.530Z] 
[2021-02-19T07:01:21.530Z]   _____          _
[2021-02-19T07:01:21.530Z]  / ____|        | |
[2021-02-19T07:01:21.530Z] | |     ___   __| | ___  ___ _____   __
[2021-02-19T07:01:21.530Z] | |    / _ \ / _` |/ _ \/ __/ _ \ \ / /
[2021-02-19T07:01:21.530Z] | |___| (_) | (_| |  __/ (_| (_) \ V /
[2021-02-19T07:01:21.531Z]  \_____\___/ \__,_|\___|\___\___/ \_/
[2021-02-19T07:01:21.531Z]                               Bash-20210129-7c25fce
[2021-02-19T07:01:21.531Z] 
[2021-02-19T07:01:21.531Z] 
[2021-02-19T07:01:21.531Z] ==> git version 2.17.1 found
[2021-02-19T07:01:21.531Z] ==> curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
[2021-02-19T07:01:21.531Z] Release-Date: 2018-01-24
[2021-02-19T07:01:21.531Z] Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
[2021-02-19T07:01:21.531Z] Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL 
[2021-02-19T07:01:21.531Z] ==> Jenkins CI detected.
[2021-02-19T07:01:21.531Z]     project root: .
[2021-02-19T07:01:21.531Z] --> token set from env
[2021-02-19T07:01:21.531Z]     Yaml found at: codecov.yml
[2021-02-19T07:01:21.531Z] ==> Running gcov in . (disable via -X gcov)
[2021-02-19T07:01:21.792Z] ==> Python coveragepy not found
[2021-02-19T07:01:21.792Z] ==> Searching for coverage reports in:
[2021-02-19T07:01:21.793Z]     + .
[2021-02-19T07:01:22.736Z]     -> Found 37 reports
[2021-02-19T07:01:22.737Z] ==> Detecting git/mercurial file structure
[2021-02-19T07:01:22.737Z] ==> Reading reports
[2021-02-19T07:01:22.737Z]     + ./.local/share/NuGet/v3-cache/670c1461c29885f9aa22c281d8b7da90845b38e4$ps:_api.nuget.org_v3_index.json/nupkg_microsoft.codecoverage.16.8.3.dat bytes=2859149
[2021-02-19T07:01:22.737Z]     + ./.local/share/NuGet/v3-cache/670c1461c29885f9aa22c281d8b7da90845b38e4$ps:_api.nuget.org_v3_index.json/list_microsoft.codecoverage.dat bytes=1541
[2021-02-19T07:01:22.737Z]     + ./.nuget/packages/microsoft.codecoverage/16.8.3/microsoft.codecoverage.16.8.3.nupkg bytes=2859149
[2021-02-19T07:01:22.737Z]     + ./.nuget/packages/microsoft.codecoverage/16.8.3/build/netstandard1.0/CodeCoverage/codecoveragemessages.dll bytes=35208
[2021-02-19T07:01:22.737Z]     + ./.nuget/packages/microsoft.codecoverage/16.8.3/microsoft.codecoverage.16.8.3.nupkg.sha512 bytes=88
[2021-02-19T07:01:22.737Z]     + ./.nuget/packages/microsoft.codecoverage/16.8.3/microsoft.codecoverage.nuspec bytes=972
[2021-02-19T07:01:22.737Z]     + ./target/48e43cce-813b-45ff-860a-f82cefb0bbdd/48e43cce-813b-45ff-860a-f82cefb0bbdd-coverage.cobertura.xml bytes=1433316
[2021-02-19T07:01:22.738Z]     + ./target/95f378d2-d7f6-408c-9e74-090352b9f396/95f378d2-d7f6-408c-9e74-090352b9f396-coverage.cobertura.xml bytes=1391722
[2021-02-19T07:01:22.738Z]     + ./target/cda111d7-6439-4aaf-95c9-36971a9023bf/cda111d7-6439-4aaf-95c9-36971a9023bf-coverage.cobertura.xml bytes=1377135
[2021-02-19T07:01:22.738Z]     + ./target/fb05926e-7d3e-4398-81ea-228aba00d264/fb05926e-7d3e-4398-81ea-228aba00d264-coverage.cobertura.xml bytes=1377060
[2021-02-19T07:01:22.738Z]     + ./target/1da76b80-4acf-402d-929c-e8c44132bef7/1da76b80-4acf-402d-929c-e8c44132bef7-coverage.cobertura.xml bytes=1404171
[2021-02-19T07:01:22.738Z]     + ./target/0e7caba9-5cf2-48ed-aa99-073643df26b5/0e7caba9-5cf2-48ed-aa99-073643df26b5-coverage.cobertura.xml bytes=1641702
[2021-02-19T07:01:22.738Z]     + ./target/c74bf785-6708-4e53-bb69-152da1d4c224/c74bf785-6708-4e53-bb69-152da1d4c224-coverage.cobertura.xml bytes=1377086
[2021-02-19T07:01:22.738Z]     + ./target/6d634c80-6c3e-4178-8d9f-3bc23305ec79/6d634c80-6c3e-4178-8d9f-3bc23305ec79-coverage.cobertura.xml bytes=1731856
[2021-02-19T07:01:22.738Z]     + ./target/c44ef3c6-4bf6-47a4-8931-6e67c86f0d5a/c4 [...]

2021-02-22 02:41 UTC, russcam commented
jenkins run the tests

2021-02-22 07:22 UTC, russcam commented
jenkins run the tests

2021-02-22 19:54 UTC, gregkalapos requested changes
I went through this and I agree that this can potentially be related to the activity id format and to https://github.com/elastic/apm-agent-dotnet/pull/896 and https://github.com/elastic/apm-agent-dotnet/pull/1022. But I'm still not 100% sure.

If the theory is true, then this should consistently fail - The bug where the `.End` events are not sent should basically always happen - at least when I reproduced it, it was always the case.

The `HttpCallWithW3CActivityFormat` test is now failing on Windows (both .NET Core and on Full Framework). I see you added a timeout there `mockPayloadSender.WaitForSpans(TimeSpan.FromMinutes(1));`. So this makes me think now instead of hanging, we got failing tests after 1 minute - so this proves that those tests are indeed not ok.

I tried to figure out why this happens, but locally that test is green for me on Windows. This original problem where we don't get the `End` event and the span is missing is related to the version of `System.Diagnostics.DiagnosticSource` and if it's pre `5.x`, I think we'll have the problem (see https://github.com/elastic/apm-agent-dotnet/pull/1022). Could it be that in CI we somehow end up with an older version? From what I see it should always be `5.x`, unless it's build for the startuphook - or isn't that the case? 🤔

2021-02-22 20:09 UTC, gregkalapos commented on test/Elastic.Apm.Tests/BackendCommTests/CentralConfig/CentralConfigFetcherTests.cs
> +			while (count < 60 && testLogger.LogLevelSwitch.Level == logLevel)
👍 Indeed we had a flaky test, likely related to this.

2021-02-23 06:12 UTC, russcam commented
`HttpCallWithW3CActivityFormat` is also green for me locally. 

I've added an `XUnitLogger` APM logger implementation to capture the agent logs for the test and also emit the version of `System.Diagnostics.DiagnosticSource`; it's running with 5.0.0 when it fails. I'm wondering if there's some concurrent cross-test interference/pollution happening when this test runs that sometimes results in failure. [On one failing test run](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-dotnet%2Fapm-agent-dotnet-mbp/detail/PR-1193/20/tests), it looks like the diagnostic listener didn't get called for the `HttpClient` call in the test (it did for central configuration though):

```
HttpCallWithW3CActivityFormat: {SystemInfoHelper} No /proc/self/cgroup found - the agent will not report container id
HttpCallWithW3CActivityFormat: {HttpDiagnosticListener} Current runtime is detected as Full Framework. RuntimeInformation.FrameworkDescription: .NET Framework 4.8.4018.0
HttpCallWithW3CActivityFormat: {DiagnosticInitializer} Subscribed Elastic.Apm.DiagnosticListeners.HttpDiagnosticListenerFullFrameworkImpl to `System.Net.Http.Desktop' events source
HttpCallWithW3CActivityFormat: {AbstractConfigurationReader (MockConfigSnapshot)} No transaction sample rate provided. Defaulting to '1'
HttpCallWithW3CActivityFormat: {Transaction} New Transaction instance created: Transaction{Id: 3720f0183d694847, TraceId: e07304dcd1d4c845bbdc296fe72fa4ec, ParentId: null, Name: Test, Type: Test, Outcome: Unknown, IsSampled: True}. IsSampled (True) is based on the given sampler (Sampler{ constant: True }). Start time: 2021-02-23 04:17:13.9845550 UTC (as timestamp: 1614053833984555)
HttpCallWithW3CActivityFormat: {Tracer} Starting Transaction{Id: 3720f0183d694847, TraceId: e07304dcd1d4c845bbdc296fe72fa4ec, ParentId: null, Name: Test, Type: Test, Outcome: Unknown, IsSampled: True}
HttpCallWithW3CActivityFormat: {Transaction} Ended Transaction{Id: 3720f0183d694847, TraceId: e07304dcd1d4c845bbdc296fe72fa4ec, ParentId: null, Name: Test, Type: Test, Outcome: Unknown, IsSampled: True}. Start time: 2021-02-23 04:17:13.9845550 UTC (as timestamp: 1614053833984555), End time: 2021-02-23 04:17:13.9943170 UTC (as timestamp: 1614053833994317), Duration: 9.762ms
HttpCallWithW3CActivityFormat: {HttpDiagnosticListenerImplBase} Called with key: `System.Net.Http.Desktop.HttpRequestOut.Start'
HttpCallWithW3CActivityFormat: {AbstractConfigurationReader (MockConfigSnapshot)} Using default ServerUrl: http://localhost:8200/
HttpCallWithW3CActivityFormat: {HttpDiagnosticListenerImplBase} Request URL (http://localhost:8200/config/v1/agents?service.name=xunit_execution_desktop) is filtered out - exiting
```

2021-02-23 06:35 UTC, russcam commented
I've kicked the tests off again.

Digging into `HttpHandlerDiagnosticListener`, The `"System.Net.Http.Desktop.HttpRequestOut.Ex.Stop"` key will be raised when the response content length is 0 and the request is async, which is true for the HttpCallWithW3CActivityFormat test

https://github.com/dotnet/runtime/blob/7565d60891e43415f5e81b59e50c52dba46ee0d7/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/HttpHandlerDiagnosticListener.cs#L543-L564

```c#
                        // In case reponse content length is 0 and request is async,
                        // we won't have a HttpWebResponse set on request object when this method is called
                        // http://referencesource.microsoft.com/#System/net/System/Net/HttpWebResponse.cs,525

                        // But we there will be CoreResponseData object that is either exception
                        // or the internal HTTP reponse representation having status, content and headers

                        var coreResponse = s_coreResponseAccessor(request);
                        if (coreResponse != null && s_coreResponseDataType.IsInstanceOfType(coreResponse))
                        {
                            HttpStatusCode status = s_coreStatusCodeAccessor(coreResponse);
                            WebHeaderCollection headers = s_coreHeadersAccessor(coreResponse);

                            // Manual creation of HttpWebResponse here is not possible as this method is eventually called from the
                            // HttpWebResponse ctor. So we will send Stop event with the Status and Headers payload
                            // to notify listeners about response;
                            // We use two different names for Stop events since one event with payload type that varies creates
                            // complications for efficient payload parsing and is not supported by DiagnosicSource helper
                            // libraries (e.g. Microsoft.Extensions.DiagnosticAdapter)

                            s_instance.RaiseResponseEvent(request, status, headers);
                        }
```

This response event does not check for the traceparent header however, to raise the event. like the `"System.Net.Http.Desktop.HttpRequestOut.Stop"` does (related issue: https://github.com/dotnet/runtime/issues/37124):

https://github.com/dotnet/runtime/blob/7565d60891e43415f5e81b59e50c52dba46ee0d7/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/HttpHandlerDiagnosticListener.cs#L668-L677

```c#
        private void RaiseResponseEvent(HttpWebRequest request, HttpStatusCode statusCode, WebHeaderCollection headers)
        {
            // Response event could be received several times for the same request in case it was redirected
            // IsLastResponse checks if response is the last one (no more redirects will happen)
            // based on response StatusCode and number or redirects done so far
            if (request.Headers.Get(RequestIdHeaderName) != null && IsLastResponse(request, statusCode))
            {
                this.Write(RequestStopExName, new { Request = request, StatusCode = statusCode, Headers = headers });
            }
        }
```

Still, we should at least see the start event and a span created for the call.

2021-02-23 07:30 UTC, russcam commented
@gregkalapos I think it'd be good to merge this in, as it addresses the test hangs. There are still some intermittently flaky tests happening, but we can look at addressing those separately.

2021-02-23 20:15 UTC, gregkalapos approved these changes
Ok, let's merge this.

Do I see it correctly that the `HttpCallWithW3CActivityFormat` became green after you changed the logger? Super strange :)

2021-02-23 23:41 UTC, russcam commented
> Do I see it correctly that the HttpCallWithW3CActivityFormat became green after you changed the logger? Super strange :)

It is strange. The successful test run output is as expected

```log
Elastic.Apm.Tests.HttpDiagnosticListenerTests.HttpCallWithW3CActivityFormat
    System.Diagnostics.DiagnosticSource version is System.Diagnostics.DiagnosticSource, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
    HttpCallWithW3CActivityFormat: {AbstractConfigurationReader (MockConfigSnapshot)} The agent was started without a service name. The service name will be automatically discovered.
    HttpCallWithW3CActivityFormat: {AbstractConfigurationReader (MockConfigSnapshot)} The agent was started without a service name. The automatically discovered service name is xunit_execution_desktop
    HttpCallWithW3CActivityFormat: {AbstractConfigurationReader (MockConfigSnapshot)} The agent was started without a service version. The service version will be automatically discovered.
    HttpCallWithW3CActivityFormat: {AbstractConfigurationReader (MockConfigSnapshot)} Failed to discover service version, the service version will be omitted.
    HttpCallWithW3CActivityFormat: {SystemInfoHelper} No /proc/self/cgroup found - the agent will not report container id
    HttpCallWithW3CActivityFormat: {HttpDiagnosticListener} Current runtime is detected as Full Framework. RuntimeInformation.FrameworkDescription: .NET Framework 4.8.4018.0
    HttpCallWithW3CActivityFormat: {DiagnosticInitializer} Subscribed Elastic.Apm.DiagnosticListeners.HttpDiagnosticListenerFullFrameworkImpl to `System.Net.Http.Desktop' events source
    HttpCallWithW3CActivityFormat: {AbstractConfigurationReader (MockConfigSnapshot)} No transaction sample rate provided. Defaulting to '1'
    HttpCallWithW3CActivityFormat: {Transaction} New Transaction instance created: Transaction{Id: 14f2cb02dff5c044, TraceId: a03a24070e70c44f92e5b7c613c5059a, ParentId: null, Name: Test, Type: Test, Outcome: Unknown, IsSampled: True}. IsSampled (True) is based on the given sampler (Sampler{ constant: True }). Start time: 2021-02-23 06:37:33.1505780 UTC (as timestamp: 1614062253150578)
    HttpCallWithW3CActivityFormat: {Tracer} Starting Transaction{Id: 14f2cb02dff5c044, TraceId: a03a24070e70c44f92e5b7c613c5059a, ParentId: null, Name: Test, Type: Test, Outcome: Unknown, IsSampled: True}
    Making request to: http://localhost:49215/
    HttpCallWithW3CActivityFormat: {HttpDiagnosticListenerImplBase} Called with key: `System.Net.Http.Desktop.HttpRequestOut.Start'
    HttpCallWithW3CActivityFormat: {AbstractConfigurationReader (MockConfigSnapshot)} Using default ServerUrl: http://localhost:8200/
    HttpCallWithW3CActivityFormat: {HttpDiagnosticListenerImplBase} Processing start event... Request URL: http://localhost:49215/
    HttpCallWithW3CActivityFormat: {AbstractConfigurationReader (MockConfigSnapshot)} No transaction max spans provided. Defaulting to '500'
    HttpCallWithW3CActivityFormat: {Span.c4ec8baa6cfdb847} New Span instance created: Span{Id: c4ec8baa6cfdb847, TransactionId: 14f2cb02dff5c044, ParentId: 14f2cb02dff5c044, TraceId: a03a24070e70c44f92e5b7c613c5059a, Name: GET localhost, Type: external, Outcome: Unknown, IsSampled: True}. Start time: 2021-02-23 06:37:33.1564680 UTC (as timestamp: 1614062253156468). Parent span: (null)
    HttpCallWithW3CActivityFormat: {Transaction} Starting Span{Id: c4ec8baa6cfdb847, TransactionId: 14f2cb02dff5c044, ParentId: 14f2cb02dff5c044, TraceId: a03a24070e70c44f92e5b7c613c5059a, Name: GET localhost, Type: external, Outcome: Unknown, IsSampled: True}
    HttpCallWithW3CActivityFormat: {AbstractConfigurationReader (MockConfigSnapshot)} UseElasticTraceparentHeader configuration option doesn't have a valid value - using default: True
    HttpCallWithW3CActivityFormat: {HttpDiagnosticListenerImplBase} Called with key: `System.Net.Http.Desktop.HttpRequestOut.Stop'
    HttpCallWithW3CActivityFormat: {HttpDiagnosticListenerImplBase} Processing stop event... Request URL: http://localhost:49215/
    HttpCallWithW3CActivityFormat: {Span.c4ec8baa6cfdb847} Ended Span{Id: c4ec8baa6cfdb847, TransactionId: 14f2cb02dff5c044, ParentId: 14f2cb02dff5c044, TraceId: a03a24070e70c44f92e5b7c613c5059a, Name: GET localhost, Type: external, Outcome: Success, IsSampled: True}. Start time: 2021-02-23 06:37:33.1564680 UTC (as timestamp: 1614062253156468), End time: 2021-02-23 06:37:33.1574480 UTC (as timestamp: 1614062253157448), Duration: 0.98ms
    HttpCallWithW3CActivityFormat: {Transaction} Ended Transaction{Id: 14f2cb02dff5c044, TraceId: a03a24070e70c44f92e5b7c613c5059a, ParentId: null, Name: Test, Type: Test, Outcome: Unknown, IsSampled: True}. Start time: 2021-02-23 06:37:33.1505780 UTC (as timestamp: 1614062253150578), End time: 2021-02-23 06:37:33.1828670 UTC (as timestamp: 1614062253182867), Duration: 32.289ms
```

2021-02-23 23:48 UTC, merged