#1759 Fixed crashes on some SOAP 1.2 requests when using GetBufferedInputStream
elastic/apm-agent-dotnet pull request #1811
Opened 2022-09-06 21:30 UTC by theiji

This fixes issue [1759 ](https://github.com/elastic/apm-agent-dotnet/issues/1759) crashes on some SOAP 1.2 requests when using GetBufferedInputStream

2022-09-06 21:34 UTC, apmmachine commented
## :grey_exclamation: Build Aborted
  
  > The PR is not allowed to run in the CI yet
  


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-dotnet%2Fapm-agent-dotnet-mbp%2FPR-1811/detail/PR-1811/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-dotnet%2Fapm-agent-dotnet-mbp%2FPR-1811/detail/PR-1811/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-dotnet%2Fapm-agent-dotnet-mbp%2FPR-1811/detail/PR-1811/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-dotnet%2Fapm-agent-dotnet-mbp%2FPR-1811/detail/PR-1811/1//artifacts)   [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/apm-ci/transactions/view?rangeFrom=2022-09-06T21:20:15.437Z&rangeTo=2022-09-06T21:40:15.437Z&transactionName=BUILD+apm-agent-dotnet%2Fapm-agent-dotnet-mbp%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=77edad5101f1ed8312e8848506722005&transactionId=e94885a56bcc8ce8)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-09-06T21:30:15.437+0000


* Duration: 4 min 46 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














### Steps errors [![2](https://img.shields.io/badge/2%20-red)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-dotnet%2Fapm-agent-dotnet-mbp%2FPR-1811/detail/PR-1811/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Load a resource file from a library`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://apm-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/apm-agent-dotnet/pipelines/apm-agent-dotnet-mbp/pipelines/PR-1811/runs/1/steps/87/log/?start=0">here</a></li>
<li>Description: <code>approval-list/elastic/apm-agent-dotnet.yml</code></l1>
</ul>
  
  
  
  
##### `Error signal`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://apm-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/apm-agent-dotnet/pipelines/apm-agent-dotnet-mbp/pipelines/PR-1811/runs/1/steps/95/log/?start=0">here</a></li>
<li>Description: <code>githubApiCall: The REST API call https://api.github.com/orgs/elastic/members/theiji return the message : java.lang.Exception: httpRequest: Failure connecting to the service https://api.github.com/orgs/elastic/members/theiji : httpRequest: Failure connecting to the service https://api.github.com/orgs/elastic/members/theiji : Code: 404Error: {"message":"User does not exist or is not a member of the organization","documentation_url":"https://docs.github.com/rest/reference/orgs#check-organization-membership-for-a-user"}</code></l1>
</ul>
  
  </p>
  </details>



## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.


- `run benchmark tests` : Run the benchmark test.


- `run` `elasticsearch-ci/docs` : Re-trigger the docs validation. (use unformatted text in the comment!)




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-09-07 06:18 UTC, z1c0 commented
Thanks for your contribution @theiji!
May I ask you to add a reproducer/test to your PR, please?
You can find existing tests for SOAP requests [here](https://github.com/elastic/apm-agent-dotnet/blob/main/test/Elastic.Apm.AspNetFullFramework.Tests/Soap/SoapRequestTests.cs).

2022-09-12 14:35 UTC, z1c0 commented
@theiji I was able to verify your fix - thanks again!
I think I could simply the code a little bit and added an additional test (small & large payload).
May I ask to to update your PR the way I suggested in my branch https://github.com/elastic/apm-agent-dotnet/tree/1759-bug-elasticapmaspnetfullframework-crashes-on-some-soap-requests-to-asp-net-web-service?

2022-09-12 14:44 UTC, z1c0 commented
FYI @gregkalapos - I was able to reproduce the issue and verify the fix provided here.
The underlying problem is that in [GetSoap12ActionFromInputStream](https://github.com/elastic/apm-agent-dotnet/blob/20fea7888fd3a044e13fb34c3e657d26502a6911/src/Elastic.Apm.AspNetFullFramework/Extensions/SoapRequest.cs#L85) we use an `XmlReader` to read the posted payload data. For large payloads, we end up in a situation where the `XmlReader` only reads part of the stream (as large as its internal buffer size). 

<img width="1029" alt="image" src="https://user-images.githubusercontent.com/4700296/189684006-89ec899a-f333-4b11-a95d-d8b46cdd60f8.png">

This leaves the underlying stream in a "half-read" state that, later on,  causes the internal server error. By making sure that the stream is read to the end at all times, this issue is fixed.

2022-09-12 18:55 UTC, z1c0 approved these changes
LGTM!
(It looks like you still need to sign the CLA though @theiji)

2022-09-12 19:03 UTC, gregkalapos approved these changes
LGTM as well.

@theiji please make sure you use the same e-mail address that you used for your commits when you sign the CLA - [it’s here in the 2. line](https://github.com/elastic/apm-agent-dotnet/commit/fe639a0cee39dab39067f0be855e82d6687ff033.patch).

We can merge once the CLA is signed.

2022-09-12 20:16 UTC, theiji commented
@gregkalapos sorry. Can I change e-mail address in this commits. My profile on notebook was wrong to commit. The correct is theiji@hotmail.com

2022-09-13 17:30 UTC, gregkalapos requested changes
Thanks for signing the CLA @theiji.

There is one minor issue with the changed test - details below. Sorry for missing that previously; I just noticed that after CI ran the PR (it wasn't running the PR previously due to the missing CLA).

2022-09-13 17:30 UTC, gregkalapos commented on test/Elastic.Apm.AspNetFullFramework.Tests/Soap/SoapRequestTests.cs
>  		[AspNetFullFrameworkFact]
```suggestion
		[AspNetFullFrameworkTheory]
```

Currently it fails:

```
System.InvalidOperationException : [Fact] methods are not allowed to have parameters. Did you mean to use [Theory]?
```

Due to the new parameter, it needs to be `AspNetFullFrameworkTheory`

2022-09-13 17:45 UTC, theiji commented
@gregkalapos done

2022-09-13 18:09 UTC, z1c0 commented
Thanks for hanging on @theiji - merge is imminent :-)

2022-09-13 20:03 UTC, gregkalapos approved these changes
Thanks for your contribution @theiji!

2022-09-13 20:03 UTC, merged