Fix transaction trace id not aligned when transaction is created from OTel bridge without parent
elastic/apm-agent-dotnet pull request #1882
Opened 2022-10-22 16:31 UTC by kuanpak

The is the PR for fixing OTel bridged transactions correlation bug #1881 

Just pass Tracer.StartTransactionInternal()'s traceId parameter into Transaction internal constructor in order to fix the issue, so that the elastic transaction created from OTel bridge will use the same traceId as the OTel span (Activity).

Related Unit tests are also added to verify the results.

2022-10-22 16:37 UTC, apmmachine commented
## :grey_exclamation: Build Aborted
  
  > The PR is not allowed to run in the CI yet
  


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-dotnet%2Fapm-agent-dotnet-mbp%2FPR-1882/detail/PR-1882/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-dotnet%2Fapm-agent-dotnet-mbp%2FPR-1882/detail/PR-1882/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-dotnet%2Fapm-agent-dotnet-mbp%2FPR-1882/detail/PR-1882/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-dotnet%2Fapm-agent-dotnet-mbp%2FPR-1882/detail/PR-1882/1//artifacts)   [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/apm-ci/transactions/view?rangeFrom=2022-10-22T16:22:02.232Z&rangeTo=2022-10-22T16:42:02.232Z&transactionName=BUILD+apm-agent-dotnet%2Fapm-agent-dotnet-mbp%2FPR-%7Bnumber%7D&transactionType=job&latencyAggregationType=avg&traceId=b4436a54f3021bc9a62e0bf17b03090b&transactionId=9457153336828c48)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-10-22T16:32:02.232+0000


* Duration: 5 min 1 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














### Steps errors [![2](https://img.shields.io/badge/2%20-red)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-dotnet%2Fapm-agent-dotnet-mbp%2FPR-1882/detail/PR-1882/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>


  
  
  
  
##### `Load a resource file from a library`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://apm-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/apm-agent-dotnet/pipelines/apm-agent-dotnet-mbp/pipelines/PR-1882/runs/1/steps/87/log/?start=0">here</a></li>
<li>Description: <code>approval-list/elastic/apm-agent-dotnet.yml</code></l1>
</ul>
  
  
  
  
##### `Error signal`
<ul>
<li>Took 0 min 0 sec . View more details <a href="https://apm-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/apm-agent-dotnet/pipelines/apm-agent-dotnet-mbp/pipelines/PR-1882/runs/1/steps/95/log/?start=0">here</a></li>
<li>Description: <code>githubApiCall: The REST API call https://api.github.com/orgs/elastic/members/kuanpak return the message : java.lang.Exception: httpRequest: Failure connecting to the service https://api.github.com/orgs/elastic/members/kuanpak : httpRequest: Failure connecting to the service https://api.github.com/orgs/elastic/members/kuanpak : Code: 404Error: {"message":"User does not exist or is not a member of the organization","documentation_url":"https://docs.github.com/rest/reference/orgs#check-organization-membership-for-a-user"}</code></l1>
</ul>
  
  </p>
  </details>



## :robot: GitHub comments

<details><summary>Expand to view the GitHub comments</summary>
<p>

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.


- `run benchmark tests` : Run the benchmark test.


- `run` `elasticsearch-ci/docs` : Re-trigger the docs validation. (use unformatted text in the comment!)




</p>
</details>

<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-10-24 17:52 UTC, gregkalapos requested changes
Thank you for opening this @kuanpak - super useful.

The changes look good to me, very nice PR.

The only blocker I see is the change in `oteg_bridge.feature` - we haven't communicated clearly how those work, and those changes need to be reverted (more on that in a comment below). Could you please do that?

Regarding the added test: After looking into this myself, I guess the core issue is that we did not use the `traceid` in case of a root activity was started. The test you added covers this very well, and I'd definitely keep that test. But additionally I'd also add a smaller test which tests the core issue, something like this (feel free to just add this to the PR):

```
[Fact]
public void ActivityAndTransactionTraceIdSynced()
{
	var payloadSender = new MockPayloadSender();
	using var agent = new ApmAgent(new TestAgentComponents(payloadSender: payloadSender, apmServerInfo: MockApmServerInfo.Version716,
		configuration: new MockConfiguration(enableOpenTelemetryBridge: "true")));
	var src = new ActivitySource("Test");
	string traceId;
	using (var activity = src.StartActivity("foo", ActivityKind.Server)) traceId = activity.TraceId.ToString();
	payloadSender.FirstTransaction.TraceId.Should().Be(traceId);
}
```

Again, sorry about the inconvenience regarding the gherkin tests - and thanks for the PR!

2022-10-24 17:52 UTC, gregkalapos commented on test/Elastic.Apm.Feature.Tests/Features/otel_bridge.feature
> +	Then Elastic bridged transaction trace id is equal to OTel trace id
These files are synced from https://github.com/elastic/apm/tree/main/tests/agents/gherkin-specs. We sync these files into every elastic APM Agent repo. So these files are managed in the linked repo and not here.

This means, if we change this, first we'd need to open a PR over in that repo and then it'll be synced into this one.

I just realize if you only look at this repo, you'd have no chance to know this - I'll open a PR and add a readme file to `test/Elastic.Apm.Feature.Tests`. This is totally on us and I'm sorry about this.

On the other hand, I don't think this level of detail needs to be specified. 

So, in order to proceed, I'd suggest to remove the change from this file ([otel_bridge.feature](https://github.com/elastic/apm-agent-dotnet/pull/1882/files#diff-ea36b655c118bd668317b2016c43a4e1b75b4367ba5b84ba9e99d25048b07b1f)) and from [test/Elastic.Apm.Feature.Tests/OpenTelemetryBridgeStepDefinitions.cs](https://github.com/elastic/apm-agent-dotnet/pull/1882/files#diff-4368859739d912974d2225c73bb3bd9c1f06b574ed959fde10244b4d2d944fd3) and proceed with this PR without the gherkin changes.

2022-10-24 17:52 UTC, gregkalapos commented on test/Elastic.Apm.Feature.Tests/OpenTelemetryBridgeStepDefinitions.cs
> +		[Then(@"Elastic bridged transaction trace id is equal to OTel trace id")]
As mentioned above, I suggest to remove these.

2022-10-25 12:55 UTC, kuanpak commented
Thanks @gregkalapos for reviewing this PR and providing the nice comments. I've reverted `oteg_bridge.feature` changes and aligned with your team's coding style.

2022-10-25 13:28 UTC, z1c0 reviewed
Thanks for the PR. LGTM!
I have a small ask about moving the test logic.
Also, @gregkalapos suggested adding an additional test in [this comment](https://github.com/elastic/apm-agent-dotnet/pull/1882#pullrequestreview-1153476487). Do you think you could add that as well? Very much appreciated!

2022-10-25 13:54 UTC, z1c0 approved these changes

2022-10-25 17:23 UTC, gregkalapos commented
CI green, I hit merge on this one.

The [small test](https://github.com/elastic/apm-agent-dotnet/pull/1882#pullrequestreview-1153476487) isn't in this PR, but that's fine - I'll quickly open a small follow up PR.

Thanks again @kuanpak! 🎉

2022-10-25 17:24 UTC, merged